In [1]:
import numpy as np
import pandas as pd
import os
import warnings
warnings.filterwarnings('ignore')
import logging
from pathlib import Path

In [ ]:
# base_dir = Path(__file__).resolve().parents[1]

# logs_dir = base_dir / 'logs'

# Path('logs').mkdir(exist_ok=True)
# Path('data').mkdir(exist_ok=True)

# logs_path = logs_dir / 'eda.log'

# log = logging.getLogger(__name__)
# logging.basicConfig(level=logging.INFO, format='%(asctime)s - %(levelname)s : %(message)s',
#                     datefmt='%H:%M:%S', filename=logs_path)

In [ ]:
# def load_file(filename: str = '../data/retail_store_sales.csv') -> pd.DataFrame:
#     '''Loads the csv file into the python environment as a pandas dataframe'''
#     try:
#         df = pd.read_csv(filename)
#         # log.info(f'Files successfully loaded from {filename}')
#         return df
#     except FileNotFoundError:
#         return None
#         # log.error(f'File not found! Check file path and try again')

In [ ]:
# def dataset_overview(df : pd.DataFrame):
#     '''Returns a short descriptive overview of the dataset 
#     including the shape of the dataset'''
#     # log.info(f'Number of observations : {df.shape[0]}')
#     # log.info(f'Number of columns : {df.shape[1]}')
#     # log.info(f'Dataset info : {df.info()}')
#     return {
#         'Observations' : df.shape[0],
#         'Features' : df.shape[1],
#         'Info' : df.info(),
#         'Describe' : df.describe(include='all')
#     }

In [10]:
df = pd.read_csv('../data/retail_store_sales.csv')

In [11]:
df.head()

,Transaction ID,Customer ID,Category,Item,Price Per Unit,Quantity,Total Spent,Payment Method,Location,Transaction Date,Discount Applied
0,TXN_6867343,CUST_09,Patisserie,Item_10_PAT,18.5,10.0,185.0,Digital Wallet,Online,2024-04-08,True
1,TXN_3731986,CUST_22,Milk Products,Item_17_MILK,29.0,9.0,261.0,Digital Wallet,Online,2023-07-23,True
2,TXN_9303719,CUST_02,Butchers,Item_12_BUT,21.5,2.0,43.0,Credit Card,Online,2022-10-05,False
3,TXN_9458126,CUST_06,Beverages,Item_16_BEV,27.5,9.0,247.5,Credit Card,Online,2022-05-07,NaN
4,TXN_4575373,CUST_05,Food,Item_6_FOOD,12.5,7.0,87.5,Digital Wallet,Online,2022-10-02,False

In [12]:
df.shape

(12575, 11)

In [13]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12575 entries, 0 to 12574
Data columns (total 11 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Transaction ID    12575 non-null  object
 1   Customer ID       12575 non-null  object
 2   Category          12575 non-null  object
 3   Item              11362 non-null  object
 4   Price Per Unit    11966 non-null  float64
 5   Quantity          11971 non-null  float64
 6   Total Spent       11971 non-null  float64
 7   Payment Method    12575 non-null  object
 8   Location          12575 non-null  object
 9   Transaction Date  12575 non-null  object
 10  Discount Applied  8376 non-null   object
dtypes: float64(3), object(8)
memory usage: 1.1+ MB

In [15]:
df.describe(exclude=[np.number]).T

                  count unique                            top  freq
Transaction ID    12575  12575                    TXN_2407494     1
Customer ID       12575     25                        CUST_05   544
Category          12575      8  Electric household essentials  1591
Item              11362    200                     Item_2_BEV   126
Payment Method    12575      3                           Cash  4310
Location          12575      2                         Online  6354
Transaction Date  12575   1114                     2022-05-30    26
Discount Applied   8376      2                           True  4219

In [17]:
df.describe()

       Price Per Unit      Quantity   Total Spent
count    11966.000000  11971.000000  11971.000000
mean        23.365912      5.536380    129.652577
std         10.743519      2.857883     94.750697
min          5.000000      1.000000      5.000000
25%         14.000000      3.000000     51.000000
50%         23.000000      6.000000    108.500000
75%         33.500000      8.000000    192.000000
max         41.000000     10.000000    410.000000

In [18]:
df.columns.tolist()

['Transaction ID',
 'Customer ID',
 'Category',
 'Item',
 'Price Per Unit',
 'Quantity',
 'Total Spent',
 'Payment Method',
 'Location',
 'Transaction Date',
 'Discount Applied']

In [20]:
# numeric columns
numeric_columns = df.select_dtypes(include=[np.number]).columns
for i,col in enumerate(numeric_columns,1):
    print(f'{i}. {col:<15} | Min : {df[col].min()} | Max : {df[col].max()}')

1. Price Per Unit  | Min : 5.0 | Max : 41.0
2. Quantity        | Min : 1.0 | Max : 10.0
3. Total Spent     | Min : 5.0 | Max : 410.0

In [22]:
# categorical columns
categorical_columns = df.select_dtypes(exclude=[np.number]).columns
for i,col in enumerate(categorical_columns,1):
    uniques = df[col].unique()
    print(f'{i}. {col:<20} | Unique : {df[col].nunique():<7} | Examples : {uniques[:4]}')

1. Transaction ID       | Unique : 12575   | Examples : ['TXN_6867343' 'TXN_3731986' 'TXN_9303719' 'TXN_9458126']
2. Customer ID          | Unique : 25      | Examples : ['CUST_09' 'CUST_22' 'CUST_02' 'CUST_06']
3. Category             | Unique : 8       | Examples : ['Patisserie' 'Milk Products' 'Butchers' 'Beverages']
4. Item                 | Unique : 200     | Examples : ['Item_10_PAT' 'Item_17_MILK' 'Item_12_BUT' 'Item_16_BEV']
5. Payment Method       | Unique : 3       | Examples : ['Digital Wallet' 'Credit Card' 'Cash']
6. Location             | Unique : 2       | Examples : ['Online' 'In-store']
7. Transaction Date     | Unique : 1114    | Examples : ['2024-04-08' '2023-07-23' '2022-10-05' '2022-05-07']
8. Discount Applied     | Unique : 2       | Examples : [True False nan]

In [ ]:
# missing values
missing_values = df.isnull().sum()
missing_pct = (missing_values / len(df)) * 100
missing_df = pd.DataFrame({
    'missing' : missing_values,
    'misssing_pct' : missing_pct.round(2)
}).sort_values(by='missing', ascending=False)
missing_df

                  missing  misssing_pct
Discount Applied     4199         33.39
Item                 1213          9.65
Price Per Unit        609          4.84
Total Spent           604          4.80
Quantity              604          4.80
Transaction ID          0          0.00
Customer ID             0          0.00
Category                0          0.00
Payment Method          0          0.00
Location                0          0.00
Transaction Date        0          0.00

In [ ]:
# duplicated values
df[df.duplicated()]

In [33]:
# outliers
for i, col in enumerate(numeric_columns,1):
    Q1 = df[col].quantile(0.25)
    Q3 = df[col].quantile(0.75)
    IQR = Q3 - Q1
    lower_bound = Q1 - 1.5 * IQR
    upper_bound = Q3 + 1.5 * IQR

    outliers = df[(df[col] < lower_bound) | (df[col] > upper_bound)]
    print(f'{i}. {col:<15} | Outliers : {len(outliers):<3} | Range : ({lower_bound} - {upper_bound})')

1. Price Per Unit  | Outliers : 0   | Range : (-15.25 - 62.75)
2. Quantity        | Outliers : 0   | Range : (-4.5 - 15.5)
3. Total Spent     | Outliers : 60  | Range : (-160.5 - 403.5)

In [ ]:
# examine outliers
df[(df['Total Spent'] < 0) | (df['Total Spent'] > 403)]

,Transaction ID,Customer ID,Category,Item,Price Per Unit,Quantity,Total Spent,Payment Method,Location,Transaction Date,Discount Applied
27,TXN_1599706,CUST_14,Furniture,Item_25_FUR,41.0,10.0,410.0,Credit Card,In-store,2024-03-24,True
133,TXN_2953434,CUST_25,Furniture,Item_25_FUR,41.0,10.0,410.0,Credit Card,In-store,2023-08-10,NaN
339,TXN_4374445,CUST_12,Food,Item_25_FOOD,41.0,10.0,410.0,Digital Wallet,Online,2024-10-17,NaN
869,TXN_1814138,CUST_06,Beverages,Item_25_BEV,41.0,10.0,410.0,Credit Card,In-store,2024-11-16,NaN
1060,TXN_3710081,CUST_25,Furniture,Item_25_FUR,41.0,10.0,410.0,Digital Wallet,In-store,2023-08-12,NaN
1088,TXN_1273334,CUST_22,Beverages,Item_25_BEV,41.0,10.0,410.0,Digital Wallet,In-store,2022-11-04,True
1468,TXN_1938135,CUST_17,Butchers,Item_25_BUT,41.0,10.0,410.0,Digital Wallet,In-store,2023-12-20,True
1505,TXN_8520397,CUST_12,Electric household essentials,Item_25_EHE,41.0,10.0,410.0,Credit Card,Online,2024-03-27,True
1568,TXN_8048041,CUST_14,Butchers,Item_25_BUT,41.0,10.0,410.0,Credit Card,In-store,2023-12-25,True
1950,TXN_1860120,CUST_01,Furniture,Item_25_FUR,41.0,10.0,410.0,Digital Wallet,Online,2022-01-19,True
1983,TXN_6924479,CUST_21,Patisserie,Item_25_PAT,41.0,10.0,410.0,Credit Card,Online,2022-06-11,NaN
2153,TXN_5338814,CUST_06,Milk Products,NaN,NaN,10.0,410.0,Digital Wallet,Online,2023-03-13,False
2180,TXN_1172555,CUST_08,Beverages,Item_25_BEV,41.0,10.0,410.0,Cash,In-store,2023-04-01,True
2182,TXN_4047143,CUST_16,Butchers,Item_25_BUT,41.0,10.0,410.0,Credit Card,Online,2024-04-19,NaN
2540,TXN_2208547,CUST_05,Beverages,Item_25_BEV,41.0,10.0,410.0,Credit Card,Online,2022-02-23,True
2658,TXN_1227978,CUST_03,Beverages,Item_25_BEV,41.0,10.0,410.0,Digital Wallet,In-store,2024-01-17,NaN
3036,TXN_2624160,CUST_16,Butchers,Item_25_BUT,41.0,10.0,410.0,Digital Wallet,Online,2022-06-19,True
3094,TXN_7177583,CUST_10,Butchers,Item_25_BUT,41.0,10.0,410.0,Cash,In-store,2024-08-31,False
3778,TXN_7898457,CUST_16,Beverages,Item_25_BEV,41.0,10.0,410.0,Cash,Online,2022-05-11,NaN
4526,TXN_3142066,CUST_24,Electric household essentials,Item_25_EHE,41.0,10.0,410.0,Cash,Online,2024-07-17,NaN
4780,TXN_3465682,CUST_12,Butchers,Item_25_BUT,41.0,10.0,410.0,Credit Card,In-store,2024-07-23,False
5364,TXN_8384530,CUST_02,Electric household essentials,Item_25_EHE,41.0,10.0,410.0,Credit Card,In-store,2023-12-25,False
5745,TXN_3855536,CUST_04,Computers and electric accessories,NaN,NaN,10.0,410.0,Credit Card,In-store,2024-09-27,True
5756,TXN_4286472,CUST_12,Computers and electric accessories,Item_25_CEA,41.0,10.0,410.0,Credit Card,In-store,2022-06-10,NaN
5819,TXN_4456347,CUST_16,Electric household essentials,Item_25_EHE,41.0,10.0,410.0,Cash,Online,2022-09-11,True
5969,TXN_2058333,CUST_25,Beverages,Item_25_BEV,41.0,10.0,410.0,Credit Card,In-store,2023-01-17,NaN
6174,TXN_4428473,CUST_04,Electric household essentials,Item_25_EHE,41.0,10.0,410.0,Digital Wallet,In-store,2022-07-28,True
6374,TXN_6219786,CUST_08,Electric household essentials,Item_25_EHE,41.0,10.0,410.0,Digital Wallet,Online,2022-09-05,NaN
6611,TXN_7056530,CUST_09,Food,Item_25_FOOD,41.0,10.0,410.0,Credit Card,Online,2022-08-15,NaN
6785,TXN_6513125,CUST_14,Beverages,Item_25_BEV,41.0,10.0,410.0,Cash,Online,2023-05-20,False
7272,TXN_4858882,CUST_19,Electric household essentials,Item_25_EHE,41.0,10.0,410.0,Digital Wallet,Online,2023-12-20,True
7372,TXN_8830035,CUST_17,Furniture,Item_25_FUR,41.0,10.0,410.0,Digital Wallet,Online,2022-07-05,True
7520,TXN_9553259,CUST_20,Food,Item_25_FOOD,41.0,10.0,410.0,Cash,In-store,2023-05-01,NaN
7716,TXN_9628331,CUST_04,Food,Item_25_FOOD,41.0,10.0,410.0,Credit Card,Online,2022-09-03,NaN
7769,TXN_8688342,CUST_12,Furniture,Item_25_FUR,41.0,10.0,410.0,Digital Wallet,Online,2024-04-20,True
8076,TXN_3858239,CUST_23,Food,Item_25_FOOD,41.0,10.0,410.0,Cash,In-store,2022-09-08,True
8508,TXN_4771109,CUST_21,Electric household essentials,NaN,NaN,10.0,410.0,Digital Wallet,In-store,2022-07-03,True
8596,TXN_2288041,CUST_24,Food,NaN,NaN,10.0,410.0,Digital Wallet,In-store,2023-09-02,False
8611,TXN_3342443,CUST_08,Butchers,Item_25_BUT,41.0,10.0,410.0,Credit Card,In-store,2023-10-03,True
8845,TXN_4208189,CUST_23,Butchers,Item_25_BUT,41.0,10.0,410.0,Cash,In-store,2022-06-07,False
8852,TXN_9745509,CUST_01,Patisserie,Item_25_PAT,41.0,10.0,410.0,Digital Wallet,In-store,2023-08-24,False
9214,TXN_2971834,CUST_11,Butchers,Item_25_BUT,41.0,10.0,410.0,Credit Card,Online,2022-08-29,True
9378,TXN_8837607,CUST_15,Food,Item_25_FOOD,41.0,10.0,410.0,Cash,Online,2022-11-05,NaN
9620,TXN_2386101,CUST_14,Furniture,Item_25_FUR,41.0,10.0,410.0,Digital Wallet,In-store,2025-01-04,True
9760,TXN_7254589,CUST_03,Butchers,Item_25_BUT,41.0,10.0,410.0,Cash,Online,2022-09-24,False
9884,TXN_8716794,CUST_13,Food,Item_25_FOOD,41.0,10.0,410.0,Cash,Online,2024-05-29,False
9963,TXN_6651911,CUST_22,Food,Item_25_FOOD,41.0,10.0,410.0,Digital Wallet,Online,2022-01-28,NaN
10103,TXN_1654267,CUST_03,Milk Products,Item_25_MILK,41.0,10.0,410.0,Cash,Online,2024-03-23,False
10884,TXN_5286547,CUST_16,Food,Item_25_FOOD,41.0,10.0,410.0,Digital Wallet,Online,2023-02-16,False
11093,TXN_5710989,CUST_21,Beverages,Item_25_BEV,41.0,10.0,410.0,Credit Card,In-store,2023-08-13,True
11608,TXN_7169895,CUST_07,Food,Item_25_FOOD,41.0,10.0,410.0,Digital Wallet,In-store,2022-05-11,NaN
11610,TXN_6812555,CUST_02,Beverages,Item_25_BEV,41.0,10.0,410.0,Cash,In-store,2024-01-24,True
11662,TXN_5870737,CUST_17,Computers and electric accessories,Item_25_CEA,41.0,10.0,410.0,Credit Card,Online,2024-12-24,False
11670,TXN_9777368,CUST_01,Food,Item_25_FOOD,41.0,10.0,410.0,Digital Wallet,Online,2023-10-10,True
12176,TXN_5150834,CUST_13,Electric household essentials,Item_25_EHE,41.0,10.0,410.0,Digital Wallet,Online,2022-02-24,True
12189,TXN_9791556,CUST_18,Furniture,Item_25_FUR,41.0,10.0,410.0,Digital Wallet,In-store,2024-01-27,False
12192,TXN_1657130,CUST_16,Electric household essentials,Item_25_EHE,41.0,10.0,410.0,Cash,In-store,2022-03-02,NaN
12209,TXN_1113295,CUST_11,Milk Products,Item_25_MILK,41.0,10.0,410.0,Digital Wallet,Online,2022-08-23,False
12542,TXN_7484072,CUST_02,Butchers,Item_25_BUT,41.0,10.0,410.0,Credit Card,In-store,2024-12-31,False
12557,TXN_7239201,CUST_24,Beverages,Item_25_BEV,41.0,10.0,410.0,Digital Wallet,In-store,2024-05-01,False

In [ ]:
df.corr(numeric_only=True,method='spearman')

# the three numeric columns are correlated, but not enough to drop the columns, we will rather feature engineer them

                Price Per Unit  Quantity  Total Spent
Price Per Unit        1.000000  0.011773     0.628833
Quantity              0.011773  1.000000     0.737002
Total Spent           0.628833  0.737002     1.000000

In [ ]:
# analyze the discount applied column
df[df['Discount Applied'].isna()]

,Transaction ID,Customer ID,Category,Item,Price Per Unit,Quantity,Total Spent,Payment Method,Location,Transaction Date,Discount Applied
3,TXN_9458126,CUST_06,Beverages,Item_16_BEV,27.5,9.0,247.5,Credit Card,Online,2022-05-07,NaN
5,TXN_7482416,CUST_09,Patisserie,NaN,NaN,10.0,200.0,Credit Card,Online,2023-11-30,NaN
14,TXN_2490363,CUST_09,Milk Products,Item_16_MILK,27.5,2.0,55.0,Digital Wallet,Online,2022-05-22,NaN
15,TXN_1809665,CUST_14,Beverages,NaN,24.5,NaN,NaN,Credit Card,In-store,2022-05-11,NaN
17,TXN_9634894,CUST_15,Milk Products,NaN,NaN,10.0,275.0,Digital Wallet,Online,2022-04-17,NaN
...,...,...,...,...,...,...,...,...,...,...,...
12562,TXN_7422454,CUST_07,Butchers,NaN,33.5,NaN,NaN,Cash,Online,2023-04-15,NaN
12568,TXN_1096134,CUST_06,Food,Item_4_FOOD,9.5,8.0,76.0,Digital Wallet,In-store,2022-06-11,NaN
12570,TXN_9347481,CUST_18,Patisserie,Item_23_PAT,38.0,4.0,152.0,Credit Card,In-store,2023-09-03,NaN
12572,TXN_5306010,CUST_11,Butchers,Item_7_BUT,14.0,10.0,140.0,Cash,Online,2024-08-24,NaN
12574,TXN_2407494,CUST_23,Food,Item_9_FOOD,17.0,3.0,51.0,Cash,Online,2022-08-06,NaN

In [ ]:
# fix discount applied column
df['Discount Applied'].fillna(value='Not Specified', inplace=True)

In [ ]:
df[df['Item'].isna()]
# the missing rows in items, price per unit, quantity and total spent are 
# very similar, therefore, we drop all those rows

,Transaction ID,Customer ID,Category,Item,Price Per Unit,Quantity,Total Spent,Payment Method,Location,Transaction Date,Discount Applied
5,TXN_7482416,CUST_09,Patisserie,NaN,NaN,10.0,200.0,Credit Card,Online,2023-11-30,Not Specified
7,TXN_1372952,CUST_21,Furniture,NaN,33.5,NaN,NaN,Digital Wallet,In-store,2024-04-02,True
11,TXN_5422631,CUST_09,Milk Products,NaN,NaN,8.0,52.0,Digital Wallet,In-store,2025-01-12,True
15,TXN_1809665,CUST_14,Beverages,NaN,24.5,NaN,NaN,Credit Card,In-store,2022-05-11,Not Specified
17,TXN_9634894,CUST_15,Milk Products,NaN,NaN,10.0,275.0,Digital Wallet,Online,2022-04-17,Not Specified
...,...,...,...,...,...,...,...,...,...,...,...
12527,TXN_1069238,CUST_23,Food,NaN,5.0,NaN,NaN,Digital Wallet,In-store,2022-08-13,False
12552,TXN_4823896,CUST_05,Milk Products,NaN,8.0,NaN,NaN,Cash,In-store,2022-07-21,False
12556,TXN_4397672,CUST_04,Beverages,NaN,41.0,NaN,NaN,Credit Card,Online,2024-11-28,True
12562,TXN_7422454,CUST_07,Butchers,NaN,33.5,NaN,NaN,Cash,Online,2023-04-15,Not Specified
12564,TXN_2153066,CUST_17,Electric household essentials,NaN,29.0,NaN,NaN,Digital Wallet,In-store,2024-03-28,False

In [ ]:
# drop all rows with missing columns
df.dropna(how='any',inplace=True,axis=0)

In [ ]:
# check again for missing values
df.isnull().sum()

# no missing data now after cleaning

Transaction ID      0
Customer ID         0
Category            0
Item                0
Price Per Unit      0
Quantity            0
Total Spent         0
Payment Method      0
Location            0
Transaction Date    0
Discount Applied    0
dtype: int64

In [69]:
# feature engineering

# one - hot encode low cardinal features - payment method, location, discount applied
pd.get_dummies(data=df, columns=['Payment Method','Location','Discount Applied'],
                                    dtype=int)

,Transaction ID,Customer ID,Category,Item,Price Per Unit,Quantity,Total Spent,Transaction Date,Payment Method_Cash,Payment Method_Credit Card,Payment Method_Digital Wallet,Location_In-store,Location_Online,Discount Applied_False,Discount Applied_True,Discount Applied_Not Specified
0,TXN_6867343,CUST_09,Patisserie,Item_10_PAT,18.5,10.0,185.0,2024-04-08,0,0,1,0,1,0,1,0
1,TXN_3731986,CUST_22,Milk Products,Item_17_MILK,29.0,9.0,261.0,2023-07-23,0,0,1,0,1,0,1,0
2,TXN_9303719,CUST_02,Butchers,Item_12_BUT,21.5,2.0,43.0,2022-10-05,0,1,0,0,1,1,0,0
3,TXN_9458126,CUST_06,Beverages,Item_16_BEV,27.5,9.0,247.5,2022-05-07,0,1,0,0,1,0,0,1
4,TXN_4575373,CUST_05,Food,Item_6_FOOD,12.5,7.0,87.5,2022-10-02,0,0,1,0,1,1,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12570,TXN_9347481,CUST_18,Patisserie,Item_23_PAT,38.0,4.0,152.0,2023-09-03,0,1,0,1,0,0,0,1
12571,TXN_4009414,CUST_03,Beverages,Item_2_BEV,6.5,9.0,58.5,2022-08-12,1,0,0,0,1,1,0,0
12572,TXN_5306010,CUST_11,Butchers,Item_7_BUT,14.0,10.0,140.0,2024-08-24,1,0,0,0,1,0,0,1
12573,TXN_5167298,CUST_04,Furniture,Item_7_FUR,14.0,6.0,84.0,2023-12-30,1,0,0,0,1,0,1,0
12574,TXN_2407494,CUST_23,Food,Item_9_FOOD,17.0,3.0,51.0,2022-08-06,1,0,0,0,1,0,0,1

In [ ]:
# analyze the transaction date column
df['Transaction Date'] = df['Transaction Date'].dt.days_in_month